"""empty message

Revision ID: 04caf1518a41
Revises: 8206ad4fe91f
Create Date: 2021-08-17 15:44:29.281763

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '04caf1518a41'
down_revision = '8206ad4fe91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attachment', 'originator_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('department', sa.Column('department_description', sa.String(length=300), nullable=True))
    op.alter_column('task', 'assignee_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task', 'assignee_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('department', 'department_description')
    op.alter_column('attachment', 'originator_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
